In [4]:
import torch
import numpy as np

In [3]:
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name())
else:
    print("⚠️ GPU is NOT active! Go to Runtime → Change runtime type → GPU")


CUDA available: False
⚠️ GPU is NOT active! Go to Runtime → Change runtime type → GPU


In [5]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[2.1715e-18, 2.3081e-12, 1.8590e+34, 7.7767e+31],
        [1.7181e+19, 1.8990e+28, 1.5766e-19, 2.1707e-18],
        [4.5447e+30, 3.0750e+29, 1.9284e+31, 1.8891e+31]])


In [6]:
zeros = torch.zeros(2, 3)
print(zeros, "\n\n")

ones = torch.ones(2, 3)
print(ones, "\n\n")

torch.manual_seed(1729)
rand_tensor = torch.rand(2, 3)
print(rand_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 


tensor([[1., 1., 1.],
        [1., 1., 1.]]) 


tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [7]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

random5 = torch.rand(2, 3)
print(random5)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])


In [8]:
x = torch.empty(2, 2, 3)
print(x, "\n\n")
print(x.shape)

empty_like_x = torch.empty_like(x)
print(empty_like_x, "\n\n")
print(empty_like_x.shape)

ones_like_x = torch.ones_like(x)
print(ones_like_x, "\n\n")
print(ones_like_x.shape)

rand_like_x = torch.rand_like(x)
print(rand_like_x, "\n\n") 
print(rand_like_x.shape)

tensor([[[-1.5559e-36,  4.3084e-41,  2.3119e-27],
         [ 0.0000e+00,  2.6754e-27,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  2.6747e-27,  0.0000e+00]]]) 


torch.Size([2, 2, 3])
tensor([[[ 2.2989e-27,  0.0000e+00,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00,  0.0000e+00]],

        [[ 1.3593e-43,  0.0000e+00,  2.6748e-27],
         [ 0.0000e+00, -1.5559e-36,  4.3084e-41]]]) 


torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 


torch.Size([2, 2, 3])
tensor([[[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]],

        [[0.5062, 0.8469, 0.2588],
         [0.2707, 0.4115, 0.6839]]]) 


torch.Size([2, 2, 3])


In [9]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a, "\n\n")

b = torch.rand((3, 2), dtype=torch.float64) * 20
print(b, "\n\n")

c = b.to(torch.int32)
print(c, "\n\n")


tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16) 


tensor([[11.2406, 11.2083],
        [11.6692, 18.3283],
        [ 0.2118, 18.4972]], dtype=torch.float64) 


tensor([[11, 11],
        [11, 18],
        [ 0, 18]], dtype=torch.int32) 




In [10]:
tensor = torch.rand(3,4, device='cuda' if torch.cuda.is_available() else 'cpu', requires_grad=True)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"Tensor requires grad: {tensor.requires_grad}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Tensor requires grad: True


In [11]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones, "\n\n")
print(twos, "\n\n")
print(threes, "\n\n")
print(fours, "\n\n")
print(sqrt2s)


tensor([[1., 1.],
        [1., 1.]]) 


tensor([[2., 2.],
        [2., 2.]]) 


tensor([[3., 3.],
        [3., 3.]]) 


tensor([[4., 4.],
        [4., 4.]]) 


tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [12]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)
c = a @ b  # matrix multiplication
print(a, "\n\n")
print(b, "\n\n")
print(c, "\n\n")

tensor([[0.7357, 0.0381, 0.2138],
        [0.5395, 0.3686, 0.4007]]) 


tensor([[0.7220, 0.8217],
        [0.2612, 0.7375],
        [0.8328, 0.8444]]) 


tensor([[0.7192, 0.8132],
        [0.8195, 1.0535]]) 




In [13]:
# torch.manual_seed=1729
a = torch.randint(low=0, high=12, size=(4,6))
print(a, "\n\n")

print(f"first row: {a[0]}\n")
print(f"first column: {a[:,0]}\n")
print(f"last column: {a[:, -1]}\n")

a[:, 2] = 6404
print(a, "\n\n")

tensor([[ 4,  1, 11,  6,  7,  3],
        [ 1, 10, 11, 11,  3,  9],
        [ 6,  1,  9, 10,  4,  1],
        [ 5, 11,  8,  0,  1,  7]]) 


first row: tensor([ 4,  1, 11,  6,  7,  3])

first column: tensor([4, 1, 6, 5])

last column: tensor([3, 9, 1, 7])

tensor([[   4,    1, 6404,    6,    7,    3],
        [   1,   10, 6404,   11,    3,    9],
        [   6,    1, 6404,   10,    4,    1],
        [   5,   11, 6404,    0,    1,    7]]) 




In [14]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6]])
print(x, "\n\n")
print(y, "\n\n")

result = torch.cat((x, y), dim=0)
print(result, "\n\n")

# result_2 = torch.stack((x, y), dim=0)

# print(result_2, "\n\n")

tensor([[1, 2],
        [3, 4]]) 


tensor([[5, 6]]) 


tensor([[1, 2],
        [3, 4],
        [5, 6]]) 




In [15]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))


5.750483989715576 <class 'float'>


In [16]:
ten = torch.ones(3, 4)
print((ten), "\n\n")

ten.add_(5)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 




tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [17]:
t = torch.ones(10)
print(t, "\n\n")

n = t.numpy()
print(n, "\n\n")

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) 


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 




In [18]:
t.add_(5)
print(t, "\n\n")
print(n, "\n\n")

np.add(n, 10, out=n)
print(n, "\n\n")
print(t, "\n\n")

tensor([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]) 


[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.] 


[16. 16. 16. 16. 16. 16. 16. 16. 16. 16.] 


tensor([16., 16., 16., 16., 16., 16., 16., 16., 16., 16.]) 




In [19]:
if torch.cuda.is_available():
   tensor = tensor.to('cuda')
   print(f"Device tensor is stored on: {tensor.device}")

In [20]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)
print(a.shape)
print(b.shape)


torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [21]:
a = torch.rand(1, 20)
print(a.shape)
print(f"a: {a}", "\n\n")

b = a.squeeze(0)
print(b.shape)
print(f"b: {b}", "\n\n")

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)


torch.Size([1, 20])
a: tensor([[0.8992, 0.2347, 0.1899, 0.4067, 0.1519, 0.1506, 0.9585, 0.7756, 0.8973,
         0.4929, 0.2367, 0.8194, 0.4509, 0.2690, 0.8381, 0.8207, 0.6818, 0.5057,
         0.9335, 0.9769]]) 


torch.Size([20])
b: tensor([0.8992, 0.2347, 0.1899, 0.4067, 0.1519, 0.1506, 0.9585, 0.7756, 0.8973,
        0.4929, 0.2367, 0.8194, 0.4509, 0.2690, 0.8381, 0.8207, 0.6818, 0.5057,
        0.9335, 0.9769]) 


torch.Size([2, 2])
torch.Size([2, 2])


In [6]:
a = torch.ones(4, 3, 2)
print(a, "\n\n")
c = a * torch.rand(3, 1) # 3-й дим = 1, 2-й дим ідентичний до a
print(c)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 


tensor([[[0.9132, 0.9132],
         [0.2545, 0.2545],
         [0.0491, 0.0491]],

        [[0.9132, 0.9132],
         [0.2545, 0.2545],
         [0.0491, 0.0491]],

        [[0.9132, 0.9132],
         [0.2545, 0.2545],
         [0.0491, 0.0491]],

        [[0.9132, 0.9132],
         [0.2545, 0.2545],
         [0.0491, 0.0491]]])


In [7]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # спроба помножити a * b призведе до помилки під час виконання
c = b.unsqueeze(1)       # змінити на двовимірний тензор, додавши в кінці новий dim
print(c.shape)
print(a * c)             # трансляція знову працює!


torch.Size([3, 1])
tensor([[[0.1383, 0.1383],
         [0.5293, 0.5293],
         [0.9671, 0.9671]],

        [[0.1383, 0.1383],
         [0.5293, 0.5293],
         [0.9671, 0.9671]],

        [[0.1383, 0.1383],
         [0.5293, 0.5293],
         [0.9671, 0.9671]],

        [[0.1383, 0.1383],
         [0.5293, 0.5293],
         [0.9671, 0.9671]]])


In [8]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# також може викликати його як метод у модулі torch:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)


torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])
