In [16]:
import torch
import numpy as np

In [15]:
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name())
else:
    print("⚠️ GPU is NOT active! Go to Runtime → Change runtime type → GPU")


CUDA available: False
⚠️ GPU is NOT active! Go to Runtime → Change runtime type → GPU


In [3]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
zeros = torch.zeros(2, 3)
print(zeros, "\n\n")

ones = torch.ones(2, 3)
print(ones, "\n\n")

torch.manual_seed(1729)
rand_tensor = torch.rand(2, 3)
print(rand_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 


tensor([[1., 1., 1.],
        [1., 1., 1.]]) 


tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [5]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

random5 = torch.rand(2, 3)
print(random5)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])


In [6]:
x = torch.empty(2, 2, 3)
print(x, "\n\n")
print(x.shape)

empty_like_x = torch.empty_like(x)
print(empty_like_x, "\n\n")
print(empty_like_x.shape)

ones_like_x = torch.ones_like(x)
print(ones_like_x, "\n\n")
print(ones_like_x.shape)

rand_like_x = torch.rand_like(x)
print(rand_like_x, "\n\n") 
print(rand_like_x.shape)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]) 


torch.Size([2, 2, 3])
tensor([[[-1.3213e+05,  1.2556e-42,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]) 


torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 


torch.Size([2, 2, 3])
tensor([[[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]],

        [[0.5062, 0.8469, 0.2588],
         [0.2707, 0.4115, 0.6839]]]) 


torch.Size([2, 2, 3])


In [7]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a, "\n\n")

b = torch.rand((3, 2), dtype=torch.float64) * 20
print(b, "\n\n")

c = b.to(torch.int32)
print(c, "\n\n")


tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16) 


tensor([[11.2406, 11.2083],
        [11.6692, 18.3283],
        [ 0.2118, 18.4972]], dtype=torch.float64) 


tensor([[11, 11],
        [11, 18],
        [ 0, 18]], dtype=torch.int32) 




In [8]:
tensor = torch.rand(3,4, device='cuda' if torch.cuda.is_available() else 'cpu', requires_grad=True)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"Tensor requires grad: {tensor.requires_grad}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Tensor requires grad: True


In [9]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones, "\n\n")
print(twos, "\n\n")
print(threes, "\n\n")
print(fours, "\n\n")
print(sqrt2s)


tensor([[1., 1.],
        [1., 1.]]) 


tensor([[2., 2.],
        [2., 2.]]) 


tensor([[3., 3.],
        [3., 3.]]) 


tensor([[4., 4.],
        [4., 4.]]) 


tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [10]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)
c = a @ b  # matrix multiplication
print(a, "\n\n")
print(b, "\n\n")
print(c, "\n\n")

tensor([[0.7357, 0.0381, 0.2138],
        [0.5395, 0.3686, 0.4007]]) 


tensor([[0.7220, 0.8217],
        [0.2612, 0.7375],
        [0.8328, 0.8444]]) 


tensor([[0.7192, 0.8132],
        [0.8195, 1.0535]]) 




In [11]:
# torch.manual_seed=1729
a = torch.randint(low=0, high=12, size=(4,6))
print(a, "\n\n")

print(f"first row: {a[0]}\n")
print(f"first column: {a[:,0]}\n")
print(f"last column: {a[:, -1]}\n")

a[:, 2] = 6404
print(a, "\n\n")

tensor([[ 4,  1, 11,  6,  7,  3],
        [ 1, 10, 11, 11,  3,  9],
        [ 6,  1,  9, 10,  4,  1],
        [ 5, 11,  8,  0,  1,  7]]) 


first row: tensor([ 4,  1, 11,  6,  7,  3])

first column: tensor([4, 1, 6, 5])

last column: tensor([3, 9, 1, 7])

tensor([[   4,    1, 6404,    6,    7,    3],
        [   1,   10, 6404,   11,    3,    9],
        [   6,    1, 6404,   10,    4,    1],
        [   5,   11, 6404,    0,    1,    7]]) 




In [12]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6]])
print(x, "\n\n")
print(y, "\n\n")

result = torch.cat((x, y), dim=0)
print(result, "\n\n")

# result_2 = torch.stack((x, y), dim=0)

# print(result_2, "\n\n")

tensor([[1, 2],
        [3, 4]]) 


tensor([[5, 6]]) 


tensor([[1, 2],
        [3, 4],
        [5, 6]]) 




In [13]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))


5.750483989715576 <class 'float'>


In [14]:
ten = torch.ones(10)
print((ten), "\n\n")

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) 


